### PR TITLE
Minor changes for russian translation

### PR DESCRIPTION
**Pull request by AKonia**
Check it please @benfry

### CODE REVIEW

**Comment by benfry** [comment]
So this looks like a difference of opinion in how “sketch” is to be translated. Can any other Russian speakers weigh in on what's appropriate here?

**Comment by benfry** [comment]
Ok, will just have to trust you on this one.

**Comment by cansik** [comment]
@benfry Checked it with another Russian speaker (not processing user). She told me that `Эскиз` is something which is more developed than `Набросок `.  Checking yandex image search shows that `Набросок` is maybe more something like a scribble. 

I still don't know which matches better, but just to give a second input.

#### Эскиз
image

#### Набросок
image

#### sketch
image

**Comment by AKonia** [comment]
@cansik Both `Эскиз`and `Набросок` are commonly synonyms, but second is native Russian, first is taken from French and sounds more unusual. I also noticed out that Sony's Android app `Sketch` also was translated as `Набросок`. Finally I'm native Russian speaker and developer so I can surely say that both words are using only in art and has no association with programming at all.

**Pull request merged**
