### PR TITLE
FX - align to pixel grid when drawing 1 px strokes

### PR DESCRIPTION
**Pull request by JakubValtar**

### CODE REVIEW

**Comment by benfry** [comment]
Would we be better off moving everything by 0.5? (We sometimes do a `translate(0.5, 0.5)` at the top of canvas-based projects...)

**Comment by JakubValtar** [comment]
Then you would have blurred edges of shapes. It's not perfect, but there's no clear winner among the solutions I'm aware of.

**Comment by benfry** [comment]
"No clear winner" wins again.

**Comment by JakubValtar** [comment]
It's not event a "win" when there is no competition.

**Pull request merged**
