### PR TITLE
Workaround for issue #4104

### PR DESCRIPTION
**Pull request by ghjansen**
Conditional control of FBO layer, based on environment settings.
Looking forward for feedback on any adjustment required.

More info:
Issue #4104 
[Comment explainig the patch](https://github.com/processing/processing/issues/4104#issuecomment-502246089)

### CODE REVIEW

**Comment by bill32bill32-dot** [comment]
void setup() 
{
  size(screen.width, screen.height);
}

void draw() 
{
  if (mousePressed) 
  {
    fill(0);
  } 
  else 
  {
    fill(255);
  }
  ellipse(mouseX, mouseY, 80, 80);
}
			[](url)

**Comment by commonpike** [comment]
Without this, my mac powerbooks cant use P2D or P3D. I applied this patch and magically solved the issue without noticeable side effects.

Fwiw, here's a writeup of how I did that
https://stackoverflow.com/questions/57943895/processing-apply-core-patch-and-compile

**Comment by ghjansen** [comment]
I am happy to know that it helped @commonpike . Thank you for sharing!
Please let me know if you notice anything wrong while using it.
I upvoted your solution in SO.

**Comment by benfry** [comment]
We can't make use of `sun.java2d.*` classes because they're non-standard. If this is the only way to do it, these methods would need to be called via reflection, so that it can degrade gracefully if the `sun.java2d` package (or a specific class) is not available.

**Comment by ghjansen** [comment]
@benfry understood. Thank you for your feedback!
I don't know yet a different way of doing this.
ce575e9 now uses reflection to handle `sun.java2d.*`.
Please, let me know if you think it can degrade gracefully enough this way.
Also, I'm available for hire. Is there any interest?

**Comment by benfry** [comment]
Thanks for the fix, really appreciate it. I've incorporated a version of it over here: https://github.com/processing/processing4/commit/269f626f98e9a3edaf70ea67545d7456cbbf02b7 for Processing 4.x. 

@codeanticode will want to fix it up later since there's already FBO enabled/disabled code in there, but at least we have the workaround for now.

**Comment by ghjansen** [comment]
@benfry nice!
@commonpike do you mind to test with the latest changes? (ce575e9)

**Pull request closed without merging**
