### PR TITLE
Export - fix java not being embedded on 64bit

### PR DESCRIPTION
**Pull request by JakubValtar**

### CODE REVIEW

**Comment by benfry** [comment]
Good catch, thanks.

**Comment by JakubValtar** [comment]
Evil Winds of Broken Export™ brought me here–I wouldn't dare to sail these uncharted linecodes otherwise, capt'n :)

**Comment by JakubValtar** [comment]
@benfry Btw, did you mean to close it?

**Comment by benfry** [comment]
Yeah, I merged https://github.com/processing/processing/pull/4005. Isn't that the fix?

**Comment by JakubValtar** [comment]
It said closed and not merged. Fixed it for you.

**Comment by benfry** [comment]
Weird. I blame Comcast.

**Pull request merged**
