### PR TITLE
added run and stop options to editor popup

### PR DESCRIPTION
**Pull request by AbdulazizAlaa**
what i made is added two menu options to the editor popup. one options calls the handlerun function to run the processing script and the other one calls the handlestop function to stop the running script. this is added to the JavaEditor.java class.
this is enhancement is related to this issue #4253

### CODE REVIEW

**Comment by GKFX** [comment]
This is completely different to #4253. The "sketchbook" it talks about is the dialog you see when you click File&rarr;Sketchbook...; you've changed the editor context menu.

**Comment by AbdulazizAlaa** [comment]
@GKFX sorry i did not get it the first time. can i redo this or some one else has already did it.
was the feature i implemented wanted or not ??

**Comment by GKFX** [comment]
I don't think anyone will want the menu items where you've put them, since it's more convenient to just use the toolbar, so it would be best to close this pull request.
At issue #4253, Akarshit said that he was going to work on it himself, but if you comment on that issue and offer to do it instead he might be happy with that. Good luck with your work on Processing anyway!

**Comment by Akarshit** [comment]
@AbdulazizAlaa 
Just to clarify more #4253 was about the pop-up menu one should get when right clicking on the items in sketchbook. When one opens the sketchbook s/he could see the folders and sketches in their sketchbook. That issue talks about the pop-up that one should get when right clicking on any of those items. 
I would be happy to help you if you need anything to implement #4253.

**Comment by AbdulazizAlaa** [comment]
@Akarshit Thank you very much i will look at again next week and hopefully finish it.

**Comment by GKFX** [comment]
Btw, you mentioned some issues with committing changes to PDE.properties; here's an example of how to do it: https://github.com/processing/processing/commit/2c5206c5a2c336e1bb044f6cc594d06417893fb6.

**Comment by benfry** [comment]
Not sure why we'd add these to the ctrl-click menu... Folks should use the shortcut or the menu option that's already available.

**Pull request closed without merging**
