### PR TITLE
AutoFormat.java, Mk III

### LINKED ISSUE #1041: Auto Format adds extra indent
_Original author: mkmori...@gmail.com (February 25, 2012 05:47:28)_

Another MINOR (but weird) Auto Format thing--even more trivial than my &quot;} else {&quot; thing, Issue 325....

Copy &amp; paste the bit of code below--including curly brackets--into the IDE and Auto Format: The &quot;camera.beginHUD();&quot; line will have an extra indent! (1.5.1 &amp; 2.0a4)

FWIW!

{ //Must be at least one indent already....
  box(a); //intervening comment--comments could all be on same line with code....
  //blah blah
  //blah blah a

    box(b); //Autoformat: Code with &quot;a&quot; near the end--&quot;);&quot; doesn't matter--followed by comments ending in &quot;a&quot; plus one or more blank lines force an extra indent here!
  box(c);
  //Any matching alphanumeric character seems to do it....
}

_Original issue: http://code.google.com/p/processing/issues/detail?id=1003_

### LINKED ISSUE #2540: Autoformat deletes the last line of this code.
````Java
KeyEvent.VK_BACK_SPACE,
KeyEvent.VK_DELETE,    
KeyEvent.VK_RIGHT,     
KeyEvent.VK_LEFT,      
KeyEvent.VK_UP,        
KeyEvent.VK_DOWN,      
KeyEvent.VK_HOME,      
KeyEvent.VK_END,       
KeyEvent.VK_SHIFT,     
````

### PR DESCRIPTION
**Pull request by GKFX**
This is a finished copy of what was #2560.
Fix #2540, fix #1041.

### CODE REVIEW

**Comment by GKFX** [comment]
Done!

**Comment by GKFX** [comment]
Just to review what's happened:
* Line overflow indent mechanism replaced, including special array handling. Arrays need not be split over many lines now, although if an array is split it will be formatted like that.
* `s_ind` and `ind` converted to `boolean` – they were int arrays holding only 0 and 1.
* Do-while loops properly handled so they appear as
````java
do {
  f;
} while (a);
````
* `castFlags` removed – didn't seem very useful as it only looked at a few types. Replaced by a check for if-for-while structures
* Delete `get_string` entirely, as it's useless.
* Neaten/clarify stuff.
* Split `lookup` into two methods: bufStarts and bufEnds.
* Ensure that no code is deleted.
* Prevent exceptions on many consecutive single-line ifs. (`if(a)\n if(a)\n if(a)\n if(a)\n ..."). It's unusual code, but there shouldn't be an exception.
* Avoid removing the whole margin for labels: that's a C convention I haven't seen in Java.

**Comment by GKFX** [comment]
Brief close after noticing what may be significant typo. Didn't do any harm in testing but worth correcting.

**Comment by GKFX** [comment]
Actually, it's not a problem. In fact, it's probably an improvement.

**Comment by benfry** [comment]
Thanks! Merging; fingers crossed.

**Pull request merged**
