### PR TITLE
Now the cursor moves when the line is changed after a long line

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #3148 

Though this fixes the current issue there is a lot of  buggy areas in horizontal offset .
It would be nice if the author can document these function in detail so that they can be made bug free.

### CODE REVIEW

**Comment by benfry** [comment]
The author is not part of the project, it's old/abandoned code: http://syntax.jedit.org/

**Comment by Akarshit** [comment]
So do you have any plan/idea of redoing this with something better or atleast well maintained.

**Comment by benfry** [comment]
Of course, but it's been 14 years, and nobody's had a chance to execute on the plan.

**Comment by Akarshit** [comment]
@benfry Ok i will open an issues for this, but i won't be able to work on this right now as exams are starting. Hopefully someone would like to implement this.

**Pull request merged**
