### PR TITLE
update issue template -- correct forum link

### PR DESCRIPTION
**Pull request by jeremydouglass**
changes link to not rely on subdomain autoforwarding

### CODE REVIEW

**Comment by jeremydouglass** [comment]
The follow-on update would be to migrate to their new issue templates, which are now authored with a builder and stored as YAML in .github/ISSUE_TEMPLATE/

I would do it, but the recommended way to generate those files is to use their web wizard directly on the repo -- and I am not a repo member.

https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by benfry** [comment]
Thanks; the builder thing sounds more useful, though we'd do that over in the 4.x repo.

**Comment by jeremydouglass** [comment]
> we'd do that over in the 4.x repo.

Great. If you would like me to set it up on that repo, I will just need to be a repo member at least temporarily in order to use their UI. Just let me know.

**Comment by benfry** [comment]
Thanks, happy to do that—let me know where I need to set access for you, or feel free to reach out via email: fry at processing dot org.

**Pull request merged**
