### PR TITLE
Italian Translation - PDE_it.properties

### PR DESCRIPTION
**Pull request by scollovati**
I added the it files and configurations and then I translated in Italian the .properties file.

### CODE REVIEW

**Comment by benfry** [comment]
Fantastic! Thank you so much.

**Comment by scollovati** [comment]
You're welcome!

In the next release I'll double check that everything is fine.

**Comment by benfry** [comment]
Terrific, thanks again.

**Comment by scollovati** [comment]
Sorry to reply so late: I checked this new release https://github.com/processing/processing/releases/tag/processing-0263-3.3.6 and everything is fine.

**Comment by benfry** [comment]
Great, thank you!

**Pull request merged**
