### PR TITLE
Fix for the scrolling issue

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #3248

### CODE REVIEW

**Comment by Akarshit** [comment]
Sorry i mixed two PR's, if the progress bar one isn't getting accepted i will modify this one.

**Comment by benfry** [comment]
Can you update this (with just the scrolling changes) and I can apply it?

**Comment by Akarshit** [comment]
@benfry the other branch that is in this PR has already been merged so it won't be a problem. But i would recommend not to merge this as major changes in CM are on the way and then depending on the performance I will fix the issue.

**Comment by benfry** [comment]
Ok, but as much as possible, do those Manager fixes incrementally. If you give me a massive PR, I can't review it, or it takes far more time to do it.

**Pull request closed without merging**
