### PR TITLE
sphere detail light syphon example

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by GKFX** [comment]
@tiagmoraismorgado I think that examples go into [processing/processing-docs](https://github.com/processing/processing-docs).  Also, you need to make sure your code is formatted properly; lines 17 and 18 should each be split into 4 separate lines.

**Comment by tiagmoraismorgado** [comment]
@GKFX please check if i didn't say like some random crap. cheers

**Comment by GKFX** [comment]
I'm not an official Processing person, so I'm not actually sure who you should submit this to; normally, examples go in the processing-docs repository that I linked above. But your example uses the Processing Syphon library, so probably you should be submitting a pull request to https://github.com/Syphon/Processing, not here.
Also, don't just create files in the root directory of the git repository; work out where the file is supposed to go and create it there.

**Comment by tiagmoraismorgado** [comment]
sure. is there a way you can help me moving it there? cheers

**Comment by GKFX** [comment]
Just open an issue in that repository and ask if they want to use this example. If they do, they'll tell you what to do next.

**Comment by codeanticode** [comment]
@tiagmoraismorgado I will be happy to add your example to the Syphon library if you create the PR in the [Processing Syphon repo](https://github.com/Syphon/Processing).

**Pull request closed without merging**
