### PR TITLE
Fix for #5625 - Made tab widths consistent across renderers

### PR DESCRIPTION
**Pull request by liquid600pgm**
Fortunately this is a very easy fix, just replace all tabs with spaces (I chose 4 as this is what I use as my tab width in text editors, however this should be subject to change. Maybe make a `tabWidth()` function?)

### CODE REVIEW

**Comment by benfry** [comment]
Interesting fix… I'd rather get to the source of the problem, but I think this is rare enough that it's ok to go this route.

**Comment by liquid600pgm** [comment]
I know that this fix is not very accurate, because tabs are supposed to help with making tables etc. but I might create a better fix at some other point in time.

**Comment by clankill3r** [comment]
I am pretty sure you just broke `textWidth`, you need to replace the tabs there as well.

**Comment by jeremydouglass** [comment]
Don't break `textWidth`! I like the idea of this change, but if it comes down to a choice I personally I think supporting dynamic typography logic is more important than cross-renderer consistency. My two cents.

**Comment by liquid600pgm** [comment]
@clankill3r I didn't think about that possibility, I'll make a new version of this, fixing the broken fix that breaks things.

**Comment by benfry** [comment]
Ok, backing out that fix. We'd need to add that hack to 4-5 places in the code, and it still wouldn't cover text from `char[]` arrays and it doesn't actually implement tab support anyway.

**Pull request merged**
