### PR TITLE
Fix 3D on contemporary versions of Linux (fixes #5308)

### LINKED ISSUE #5308: P3D don't work on AMD dynamic switchable graphics
## Description

I have a laptop with a low end AMD graphicial card R5 230M. Since my Intel integrated card gave me a slow performance in a program, I tried to use AMD card to render this file. (Using PRIME) Sadly, it can not work. 

## Expected Behavior

The program can normally run.

## Current Behavior

Normal window does not open, and the error informations are:
`
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
	at com.jogamp.opengl.GLProfile.getGL2ES2(GLProfile.java:909)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:192)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:136)
	at processing.core.PApplet.initSurface(PApplet.java:10889)
	at processing.core.PApplet.runSketch(PApplet.java:10776)
	at processing.core.PApplet.main(PApplet.java:10476)
`

## Steps to Reproduce

1. Write a processing file, use P2D or P3D.
2. DRI_PRIME=1 processing-java --sketch=../_theTestFile_/ --run

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Arch Linux
* Other information:
I'm using PRIME to manage hybrid graphics.

### PR DESCRIPTION
**Pull request by gohai**
Compiled from https://github.com/gohai/jogl/tree/processing at 0bd5acc.

### CODE REVIEW

**Comment by benfry** [comment]
What's this one mean, exactly?

**Comment by gohai** [comment]
A recent version of the Mesa OpenGL software changed the renderer string reported to GL applications. This broke JOGL which used this as an indicator to enable certain quirks that appear to be needed with Mesa. From looking at bug reports, this predominantly caused problems for users with dedicated AMD graphics cards.

**Comment by serebit** [comment]
THANK YOU. This Mesa issue was the only thing keeping me from using Processing on my Linux installation.

**Comment by gohai** [comment]
@serebit Could you test this `jogl-all.jar` file to see if it still works with your setup? https://sukzessiv.net/~gohai/p5/jogl-all.jar Please also report the output of `glxinfo`. Thanks!

**Comment by serebit** [comment]
Unfortunately, @gohai, the update still didn't fix Processing for me when I try to use the OpenGL renderers. Now when I run a sketch with an OpenGL renderer selected, the JVM crashes on this line of code:
```
if(ReflectionUtil.DEBUG_STATS_FORNAME) {
```
on line 210 in GLProfile.java. The included file ([hs_err_pid32175.log](https://github.com/processing/processing/files/1944875/hs_err_pid32175.log)) is the JVM crashlog. This is the message in the console:
```
#  SIGSEGV (0xb) at pc=0x0000000000004206, pid=32175, tid=0x00007f6c53434700
#
# JRE version: OpenJDK Runtime Environment (8.0_172) (build 1.8.0_172-solus-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.172-b00 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000004206
```
Let me know if you have any ideas.

**Comment by gohai** [comment]
@serebit Did plain 3.3.7 work for you? Or both, 3.3.7 as well as the JAR file I posted are crashing?

**Comment by serebit** [comment]
@gohai Both 3.3.7 and the JAR file you posted are crashing with the same error.

**Comment by gohai** [comment]
@serebit And just to be sure I understand: prior to 3.3.7 you had the same issue as described in #5308 (`java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped at `)?

**Comment by serebit** [comment]
@gohai Here's my glxinfo: 
[glxinfo.txt](https://github.com/processing/processing/files/1948517/glxinfo.txt)

**Comment by serebit** [comment]
@gohai Correction, the `jogl-all.jar` produced by the master-branch Processing build does fix the issue. The only issue now is getting the remotely-hosted JOGL jars to contain the same fixes as yours, so that I don't have to store the jars locally in my projects.

**Comment by gohai** [comment]
@serebit Sorry, I can't follow. Can you elaborate which version is now working for you, and why this wasn't working before? Thanks.

**Comment by gohai** [comment]
@serebit There is no difference between the jogl library files in 3.3.7 and the ones in the master branch.

**Comment by gohai** [comment]
The Processing project has nothing to do with whatever is up on Maven Central. Locking this thread.

**Pull request merged**
