### PR TITLE
removing Carnivore client as per #2911 and…

### PR DESCRIPTION
**Pull request by shiffman**
Re: https://github.com/processing/processing-docs/issues/238 it seems to me that core library examples are not in the processing-docs repo but actually here so this is where Carnivore client should be removed?  Doing this as a pull request in case I'm wrong.

### CODE REVIEW

**Comment by benfry** [comment]
This is @REAS's call. I'm not sure what his plan was.

**Comment by shiffman** [comment]
Thanks, sorry if i'm making extra noise, I had an hour waiting for a home repair and thought "let me fix some stuff if i can!"

**Comment by benfry** [comment]
Nope, not at all. I just wasn't aware why he hadn't done it already, so I wanted to leave it to him.

**Comment by benfry** [comment]
Gonna go ahead and merge so we can clear things out of here. We can roll it back if need be.

**Pull request merged**
