### PR TITLE
Improved fix for Issue #4017 where tweak mode ignores some numbers in a second tab

### PR DESCRIPTION
**Pull request by erniejunior**
This is an improved version of my previous pull request after some friendly hints by @galsasson. This one has even less changes and should be more transparent.
We now maintain the ignore-lists for functions in separate lists for the different tabs.

### CODE REVIEW

**Comment by benfry** [comment]
@galsasson will wait for your initial approval...

**Comment by galsasson** [comment]
There is a warning related to the use of Collections.EMPTY_LIST. I'm not fluent with java, but I think its fine. ?
Other that that it works and fixes the issue, thanks @erniejunior

**Comment by erniejunior** [comment]
Hi, @galsasson the warning is because the EMPTY_LIST is not typed (we do not specify what type of items it contains via generics). Since it is empty it does not really matter. But we could get rid of it by using ``ignoreFunctions.add(new LinkedList<SketchParser.Range>());`` (just create an empty linked list). But I thought that explicitly spelling out that the list is empty improves readability.

**Comment by benfry** [comment]
Thanks all.

**Pull request merged**
