### PR TITLE
Add varargs versions of PApplet.min/max

### LINKED ISSUE #3027: Use varargs in min() and max()
https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java#L3724
I propose using eg max(int... a) in the method header instead of limiting to two or three arguments.

### PR DESCRIPTION
**Pull request by GKFX**
Calculate min and max variables for multiple values without manually
creating an array. Closes #3027.
Enhancement on #3033.

### CODE REVIEW

**Comment by GKFX** [comment]
@benfry Although #3027 is locked, you didn't close it so it's now locked open. Please close it.
Closing this PR as it is no longer wanted.

**Comment by benfry** [comment]
Yes, it's still open, because as I said, it's still under consideration for later in the 3.x process.

**Comment by GKFX** [comment]
OK, sorry, I missed that bit.

**Comment by benfry** [comment]
Closing this version because we'll either go all or nothing on the min/max replacement.

**Pull request closed without merging**
