### PR TITLE
PDEX: Add friendlier error message for HidingEnclosingType

### LINKED ISSUE #4228: Throw friendly error message instead of “The nested type cannot hide an enclosing type”
Hi, 

A student got this error because she named the class the same as the filename of the main sketch. Would it be possible to throw a friendlier error message? Like: "A class cannot have the same name as your the name of your sketch".

````
JitterBug bug;

void setup() {
  size(480, 120);
  bug = new JitterBug(width/2, height/2, 20);
}

void draw() {
  bug.move();
  bug.display();
}

class JitterBug {
  float x;
  float y; 
  int diameter;
  float speed = 2.5;

  JitterBug(float tempX, float tempY, int tempDiameter)  
  { 
    x = tempX;
    y = tempY;
    diameter = tempDiameter;
  }

  void move() {
      x += random(-speed, speed);
      y += random(-speed, speed);
  }

  void display() {
      ellipse(x, y, diameter, diameter);
  }
}
````

http://stackoverflow.com/questions/33902511/the-nested-type-cannot-hide-an-enclosing-type-class-java-processing

### PR DESCRIPTION
**Pull request by rzats**
Fixes #4228; is a duplicate of #4337 adjusted for some API changes.

### CODE REVIEW

**Comment by JakubValtar** [comment]
Hi @rzats, thanks for your pull request.

Could you please remove the changes made in `Problem` and the `args[0].equals(problem.getClassName())` in Simplifier? It is not necessary as it will always return true.

**Comment by rzats** [comment]
@JakubValtar: here's why these are necessary - https://github.com/processing/processing/pull/4337#issuecomment-190280293
Although I could remove the changes if this tweak is not required.

**Comment by JakubValtar** [comment]
However, you are not checking it for the name of the sketch... you are merely comparing `problem.iProblem.getArguments()[0]` with itself (which is the name of the problematic class).

```processing

class C {
  class C { // Error: The class C cannot have the same name as the name of your sketch
  }
}
```

If you want to compare with the sketch name, you would have to pass it into `getSimplifiedErrorMessage`. I would suggest changing the error message to something like 'The class "%s" cannot have the same name as your sketch or enclosing class', because the sketch name is currently not available in the Simplifier.

The simplifier will be changed soon to have more information about the sketch, so we will be able support these messages better.

**Comment by rzats** [comment]
@JakubValtar: thanks - this makes sense :wink: Updated accordingly.

**Comment by JakubValtar** [comment]
@rzats No, thank _you_ for your contribution!

@benfry Let's merge this and add TODO to check for sketch name when I'll be refactoring this.

**Comment by benfry** [comment]
Great, thanks a lot folks.

**Pull request merged**
