### PR TITLE
Fix "Could not parse -1 for --dsiplay" error

### LINKED ISSUE #5118: Could not parse -1 for --display / Could not run the sketch (Target VM failed to initialize) when starting a sketch
I get the following msg everytime I hit play:

Could not parse -1 for --display
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

I'd like to work with this package but I have no idea what to do with this error.

### PR DESCRIPTION
**Pull request by JakubValtar**
When runDisplay was set to -1 no display detection happened. Fixed it so that editor display is used.

Regression introduced in 6e9a8e0ceb5af0237885df2a860a64b0c5246a55

Fixes #5118

### CODE REVIEW

**Comment by benfry** [comment]
Thanks!

**Comment by JakubValtar** [comment]
What a horrible typo in the title – time to call it a day.

**Comment by benfry** [comment]
Not unlike the typos in the code in question…

**Comment by JakubValtar** [comment]
:sweat_smile:

**Comment by jeremydouglass** [comment]
Typo? You mean you weren't referring to DSi play? https://en.wikipedia.org/wiki/Nintendo_DSi

**Comment by JakubValtar** [comment]
Sorry, I'm more of a PS Vita guy.

**Pull request merged**
