### PR TITLE
Adding missing docs and keywords for TableRow.

### LINKED ISSUE #4332: Syntax for TableRow methods aren't recognized by the highlighter
The `TableRow` methods `setDouble()` and `setLong()` are not highlighted by the syntax highlighter in the IDE. They're also not listed in the documentation. The problem holds for the getters, too: `getLong` and `getDouble`.

Other `TableRow` methods may have the same problem -- haven't tested them all yet.

### PR DESCRIPTION
**Pull request by suheb**
Fixes #4332
Signed-off-by: Suhaib Khan suheb.work@gmail.com

### CODE REVIEW

**Comment by benfry** [comment]
@REAS This is one to be added to your keywords generator

**Comment by REAS** [comment]
This is a quick, easy fix, but it's a slippery slope that I worry about. I don't want to make it difficult, but we have many "advanced" methods across many classes that aren't in the simplified reference. Right now, all of the color coding in the PDE comes from this simplified reference list or the hardwired items. If we add these to the hardwired items, there are additional dozens that should be added too. Is that what we want to do? It's making more sense, the more I think about it.

**Comment by benfry** [comment]
Yep, agreed. `getColumnCount()` and `getColumnTitle()` are the ones to include, the others all belong in the javadoc. 

But a PR that improves the javadoc for the others would be welcome.

**Comment by suheb** [comment]
@benfry Should I remove these methods from `keywords.txt`? Also, what the correct place to add `keywords` then?

**Comment by REAS** [comment]
This is the correct spot: https://github.com/processing/processing-docs/blob/master/generate/keywords_base.txt

The `keywords.txt` file is generated, it shouldn't be edited directly.

**Comment by benfry** [comment]
@suheb Would you like to update this to add those two keywords to `keywords_base.txt`, remove them from `keywords.txt` and re-submit this patch, or should I close it?

**Comment by suheb** [comment]
@benfry Ohh, sorry about this. I thought I'd fixed this. Will update this PR and open a new one in [processing-docs](https://github.com/processing/processing-docs).

**Comment by benfry** [comment]
Great, thanks!

**Comment by suheb** [comment]
Done. Here's the other [PR](https://github.com/processing/processing-docs/pull/495). Let me know if anything's needed.

**Comment by benfry** [comment]
Thanks, I'll let the docs folks handle the other one so that they can run the necessary build scripts.

**Pull request merged**
