### PR TITLE
Fix crashing bugs that happen when the user's name has non-ASCII characters on Windows.

### PR DESCRIPTION
**Pull request by jdf**

### CODE REVIEW

**Comment by benfry** [comment]
Is this just when running from Eclipse on Windows?

**Comment by jdf** [comment]
There are two commits; one addressed an Eclipse-on-Windows bug (which could potentially fail on other platforms, too), and the other addresses a crashing bug when running a release build of the PDE.

**Comment by jdf** [comment]
Ping?

**Comment by benfry** [comment]
Thanks for the fix. Does this also cover https://github.com/processing/processing/issues/3543?

**Comment by jdf** [comment]
I can't say offhand; it depends on the codepath font loading uses.

**Comment by benfry** [comment]
(For the record, this doesn't fix #3543, which is based on a launch4j bug.)

**Comment by jdf** [comment]
argh, and thank you!

**Pull request merged**
