### PR TITLE
Possible sets the font correctly

### PR DESCRIPTION
**Pull request by Akarshit**
Possible fix for #3601

### CODE REVIEW

**Comment by benfry** [comment]
@alignedleft Can you try this one out before we merge?

**Comment by alignedleft** [comment]
Yes, will test now.

**Comment by alignedleft** [comment]
Sorry, this is still appearing as Times New Roman.

screen shot 2015-08-15 at 11 19 45 am

**Comment by Akarshit** [comment]
Nothing new here.

**Comment by Akarshit** [comment]
@alignedleft can you please try this branch now.

**Comment by alignedleft** [comment]
Font looks good on Mac!  Thanks.

screen shot 2015-08-16 at 3 01 49 pm

**Pull request merged**
