### PR TITLE
Add more Raspberry Pi related fixes to JOGL

### PR DESCRIPTION
**Pull request by gohai**
This hopefully addresses #4499 and works around the long-standing dual driver stack issue on Raspbian.

### CODE REVIEW

**Comment by benfry** [comment]
Is that a separate JOGL build you created?

**Comment by gohai** [comment]
@benfry Yes. JOGL 2.3.2 plus the [following patches](https://github.com/gohai/jogl/commits/bcm-test) on top. Hope to at least fix one more bug, before we grow the repo size because of it. I'm in touch with @xranby about incorporating those in some form or another into upstream JOGL eventually also.

**Comment by gohai** [comment]
@benfry I added one more fix, so from my perspective that'd be ready to go in. What this is improving is listed in the commit description.

**Comment by benfry** [comment]
And no activity on the JOGL front, huh? So unlikely that this will be coming in an official build anytim soon? 

@codeanticode Any other JOGL tweaks we need before incorporating a new binary like this?

**Comment by gohai** [comment]
I wouldn't hold my breath for an upcoming JOGL release ... Xerxes is in the know about those patches though

**Comment by codeanticode** [comment]
I don't have any JOGL tweaks at this time. I will look at some GL issues as soon as I can (for example #4807), but I don't those require any fixes in JOGL

I've been following reports about problems connecting to HDMI/Hires displays, e.g.: #4728 #4954, and my concern is that those might be caused by some upstream problem in JOGL...

**Comment by benfry** [comment]
#4728 and #4954 probably need some attention, since two similar reports likely means several people having issues. Though that code would be outside the jogl-all.jar that's being updated here, right? So maybe we go ahead with this stuff.

**Comment by codeanticode** [comment]
I'm pretty confident that the issues with HDMI/hi-res output are entirely separate from the RPi fixes from Gottfried.

**Comment by benfry** [comment]
I'm sure of that. The point was that this is an update to `jogl-all.jar` (the non-native part of JOGL), and those other issues all live inside the native code for macOS, right?

**Comment by codeanticode** [comment]
Ok, got it. Let me look at the hi-res issues first, because I'm not certain whether those are due to some problem with the native libs, or in the platform-specific Java code.

**Comment by benfry** [comment]
Great; thanks.

**Comment by codeanticode** [comment]
I would go ahead with the merge as, regarding the issues I mentioned before, one appears to be caused by a [hardware failure](https://github.com/processing/processing/issues/4728#issuecomment-288917615) and the other can be solved with a [resolution-setting tool](https://github.com/processing/processing/issues/4954#issuecomment-288708794).

**Pull request merged**
