### PR TITLE
Make Comment/Uncomment trigger on numpad slash

### PR DESCRIPTION
**Pull request by JakubValtar**

### CODE REVIEW

**Comment by benfry** [comment]
I suppose this is a patch, but really this is https://github.com/processing/processing/issues/2199. Are you proposing this as a band-aid until we can get to that one?

**Comment by JakubValtar** [comment]
It's not, they are two different keys. I tested on US layout and on Czech layout. Numpad slash is VK_DIVIDE and regular slash is VK_SLASH. And there is no way known to me in their terrible API to add second accelerator key to the menu item.

**Comment by benfry** [comment]
Heh, I understand that. I'm asking if this a patch to paper over #2199 so that it works on your keyboard (and others) until we have a better way of specifying a better shortcut for non-US keyboards?

**Comment by JakubValtar** [comment]
No, this has nothing to do with locale. It does not work on any numpad, because slash on numpad is considered to be a different key than slash in the letter part on every keyboard. Menu item is set up for VK_SLASH, but that does not cover numpad slash key, which is VK_DIVIDE. I belive that unless we have one listener for each key, it will not work with both keys.

**Comment by JakubValtar** [comment]
Just to make things clear: this is about numpad slash. Comment/Uncomment in other apps is often mapped to Ctrl+Slash and it always works with this key. This PR adds listener for this slash in all layouts.

keyboard2

**Comment by benfry** [comment]
I can't stop laughing that even though I said I understood that these were different keys, you still had to make an image for me. We miss you back here in Boston.

**Comment by JakubValtar** [comment]
Looks like their API is so bad it makes people dumb. I spent an hour with it before I figured it out and look at this.

**Pull request merged**
