### PR TITLE
Added the remove filter feature

### PR DESCRIPTION
**Pull request by Akarshit**
Adds a cross button on the right side of the search field in CM. Currently a "X" is being displayed but can be replaced by a icon.
Might be a cool feature. Looks like below on linux - 
screenshot from 2015-09-28 19 35 58

### CODE REVIEW

**Comment by Akarshit** [comment]
@jamesjgrady @alignedleft What are your thoughts on this one ?

**Comment by alignedleft** [comment]
@Akarshit Yes, I think this is a nice idea, as long as an icon can be used that is consistent with the rest of the UI.

**Comment by Akarshit** [comment]
@alignedleft I have added the icon. It looks like this now   
screenshot from 2015-12-11 11 25 45

**Comment by alignedleft** [comment]
This looks very nice to me. @jamesjgrady would you mind just looking and letting us know if you approve?

**Comment by jamesjgrady** [comment]
I think the x looks fine. I don't love the dark orange highlight box. Is there anything that can be done about that, or is it OS dependent?

**Comment by benfry** [comment]
Implemented for 3.2.4. 

@jamesjgrady the orange is from Linux, on the Mac we get its selection highlight color, so yeah, it's OS dependent.

**Pull request merged**
