### PR TITLE
progress bar in the status column while installing/removing/updating

### PR DESCRIPTION
**Pull request by Akarshit**
Partial fix for #4105 
This shows progressbar for all other tab except Update tab.
A few bugs still need to be fixed but the branch is useful for testing.
A screenshot of the progressbar while installing is provided below
screenshot from 2016-01-12 17 43 09

### CODE REVIEW

**Comment by alignedleft** [comment]
@Akarshit, in the Status column, it looks like the progress bar is going right to left. Either that, or the progress bar is white with a gray background. Either way, it doesn't seem to match the progress bar below right (which is gray, and moves left to right). Can you confirm?

**Comment by Akarshit** [comment]
@alignedleft The progressbar in the status column goes from left to right, with a white color and gray bakground, and the one in the description panel goes from left to right, with a gray color and background same as that of the panel.
I made it this way to be approximately consistent with the mockup below 
This behaviour if you are finding inconsistent could be easily changed. Would you like the progress bars to be as in the status column or as in the description pane?

**Comment by alignedleft** [comment]
@Akarshit Ah, I see! I find this confusing. In the "Status" column in the mockup above, light blue indicates progress, where gray is "not yet complete". So, as the installation progresses, the blue area increases and the gray area decreases. Correct?

I would recommend changing this, so the "progress" area is gray (instead of blue) and the "not yet complete" area is just the background color of the row — white, if the row is not selected, or blue, if the row is selected.

What do you think? I can mock that up if needed.

**Comment by Akarshit** [comment]
@alignedleft I have changed the progressbar to look like the figures below
screenshot from 2016-01-20 18 17 17
screenshot from 2016-01-20 18 16 42
I think this is what you intended ?

**Comment by benfry** [comment]
Going with a simpler solution from here https://github.com/processing/processing/pull/4154 that allows us to see that something is happening, but doesn't duplicate the progress indicator from the bottom panel.

**Pull request closed without merging**
