### PR TITLE
Feature: depth reading

### PR DESCRIPTION
**Pull request by JakubValtar**
Adds new hint ENABLE_DEPTH_READING, which will cause multisampled PGraphics to also downsample their depth and stencil buffers (apart from color buffer).

### CODE REVIEW

**Comment by benfry** [comment]
Isn't `DEPTH_READING` a misnomer here when it also applies to stencil buffers?

**Comment by JakubValtar** [comment]
Suggestions?

**Comment by benfry** [comment]
Something that makes more sense. :-)

**Comment by benfry** [comment]
Changed to `ENABLE_BUFFER_READING`, smart guy.

**Comment by JakubValtar** [comment]
Sounds good (in spite of the PGL function being called `readPixels`).

**Comment by benfry** [comment]
No second-guessing if you don't offer anything useful.

**Pull request merged**
