### PR TITLE
CM: Send update count to Editors

### PR DESCRIPTION
**Pull request by JakubValtar**
Requested for #3518

See https://github.com/processing/processing/issues/3518#issuecomment-143768021

### CODE REVIEW

**Comment by benfry** [comment]
Much thank you.

**Comment by JakubValtar** [comment]
I just figured out: if you open new Editor window, it should be able to get the update count and display it, so we might want to store the update count in Base and let the Editor query it on stratup.

**Comment by benfry** [comment]
The issue is that it (also) needs to be event driven, because the number will change as updates happen.

**Comment by JakubValtar** [comment]
Yes, event driven is already in place an there to stay. I was mentioning a situation when you have the PDE running and you open a new Editor window, the Editor has to get the update count somewhere because there will be no event from the Contribution Manager.

**Pull request merged**
