### PR TITLE
Report more error conditions in validateFramebuffer

### PR DESCRIPTION
**Pull request by gohai**
I don't know what any of this means, but hope the gesture will be apprechiated :)

### CODE REVIEW

**Comment by JakubValtar** [comment]
@gohai Good idea! Since we are messing with this, can you please look at [glCheckFramebufferStatus docs](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCheckFramebufferStatus.xhtml) and add all the codes which are documented there? Please don't delete the ones which are not on the page, I think they might be encountered when running older GL versions. If the constants are not in `com.jogamp.opengl.GL`, they will be in `com.jogamp.opengl.GL4`.

**Comment by gohai** [comment]
@JakubValtar Should be done. I picked `com.jogamp.opengl.GL3` since this was also was JOGL was using for those constants.

**Comment by codeanticode** [comment]
Yes, looks good.

**Comment by JakubValtar** [comment]
Nice work, please merge

**Pull request merged**
