### PR TITLE
Bar below the tab is painted

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #3599 
Please check for compatibility with mac.

### CODE REVIEW

**Comment by benfry** [comment]
I'll wait for confirmation from @alignedleft

**Comment by alignedleft** [comment]
Blue bar looks good, but why is there a gap between it and the tabs above? They should be touching; there should be no vertical space. See:

screen shot 2015-08-16 at 2 45 24 pm

Also, when you switch to the Update tab, the blue bar disappears and I see a dark gray bar. The "Updates" tab view should be consistent with the other views in this respect.

screen shot 2015-08-16 at 2 45 30 pm

**Comment by Akarshit** [comment]
@alingedleft Please check if this resolves the issue now.

**Comment by alignedleft** [comment]
No, there is still a gap.  See:

screen shot 2015-08-19 at 12 36 52 pm

Also, the dark gray 1px horizontal line just above the column names should not appear. Note it appears above, and is even more noticeable in the Updates view:

screen shot 2015-08-19 at 12 36 59 pm

**Comment by Akarshit** [comment]
@alignedleft There is a separate issue for the gap. This PR was only for that bar getting painted in all the tabs. I hope that is resolved

**Comment by alignedleft** [comment]
@Akarshit sorry for that. Yes, the blue bar is now present and working, thanks!

**Pull request merged**
