### PR TITLE
Revert "Fix 3D on contemporary versions of Linux (fixes #5308)"

### LINKED ISSUE #5308: P3D don't work on AMD dynamic switchable graphics
## Description

I have a laptop with a low end AMD graphicial card R5 230M. Since my Intel integrated card gave me a slow performance in a program, I tried to use AMD card to render this file. (Using PRIME) Sadly, it can not work. 

## Expected Behavior

The program can normally run.

## Current Behavior

Normal window does not open, and the error informations are:
`
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
	at com.jogamp.opengl.GLProfile.getGL2ES2(GLProfile.java:909)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:192)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:136)
	at processing.core.PApplet.initSurface(PApplet.java:10889)
	at processing.core.PApplet.runSketch(PApplet.java:10776)
	at processing.core.PApplet.main(PApplet.java:10476)
`

## Steps to Reproduce

1. Write a processing file, use P2D or P3D.
2. DRI_PRIME=1 processing-java --sketch=../_theTestFile_/ --run

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Arch Linux
* Other information:
I'm using PRIME to manage hybrid graphics.

### PR DESCRIPTION
**Pull request by gohai**
This reverts commit 5729c6b78f7eef6b18c6de83cb7bf9a66e4b0b63.

While this appears to have fixed GL for the AMD graphics users in #5308 it seems to have broke it for folks in #5476. It seems JOGL is abandoned these days, and I don't have the capacity to figure this out on my own. This patch reverts the "fix", so that it will continue to work on the systems that it traditionally worked on (and probably not on newer configuration not properly handled by JOGL).

### CODE REVIEW

**Comment by benfry** [comment]
Does this patch actually revert or is it just checking in the old version once again?

**Comment by gohai** [comment]
It's a `git revert`.

**Comment by benfry** [comment]
Cool, thanks.

**Comment by benfry** [comment]
Can we close #5476 as fixed by this?

**Comment by gohai** [comment]
Yes, I just did

**Comment by neilcsmith-net** [comment]
@gohai ah, crap!  That time when you help someone dig through to report an issue and break your own system in the process. :smile:  So, close #5476 and reopen #5308 ?  feckin' JOGL!

**Comment by Laaas** [comment]
Why not use something like LWJGL instead of JOGL? Or is that overkill?

**Comment by gohai** [comment]
@neilcsmith-net Yes, feel free to reopen.
@Laaas No, just a lot of work.

**Comment by neilcsmith-net** [comment]
@Laaas that's probably what has to happen, but it's a big step.  And AFAIK doesn't support ARM yet unless it's been added very recently.

Incidentally, @gohai I think the right fix for this is to revert the reversion, and look at what's going on with profiles that Processing / JOGL is trying to use backwards compatibility on a context that doesn't support it.  This is the same as macOS, right?  But it works there.

See https://discourse.processing.org/t/solved-p2d-p3d-sketches-wont-start-on-fresh-ubuntu-18-04-installation/3568/33?u=neilcsmith  Setting `jogl.disable.openglcore` to `true` also gets things working on @Architector4 machine.  Not a workaround but an interesting pointer?!

**Comment by neilcsmith-net** [comment]
@gohai I can try and look further, but can you revert this reversion of JOGL?  If the system property works for some AMD cards then it could be passed into Processing, or could look at a patch to try that on failure, but without the patch other (most?) AMD graphics users will be screwed! :smile:

On LWJGL and ARM I'd just been going on this still being open so not fully supported yet? https://github.com/LWJGL/lwjgl3/issues/206

**Comment by gohai** [comment]
@neilcsmith-net We tried the proposed patch that fixed graphics for _some_ AMD users, but this ended up breaking it for _others_. I don't have the resources to work on a better fix, hence the revert to where things were before.

Folks run Minecraft on the Pi using LWJGL, so it appears to work.

**Comment by neilcsmith-net** [comment]
@gohai I understand the history, but with the system property above it hopefully works for everyone. If you revert the patch it _cannot_ work for some, probably the majority of affected users. I'm happy to keep investigating but to do so I think the patched JOGL needs to go back in. From there we can hopefully work out why the profile is wrongly being thought to be backwards compatible. I've seen that also once recently on an nVidia card with Mesa. I suspect it's actually something in the Processing code triggering it, or at least something that can be worked around there.

**Comment by gohai** [comment]
Please send a patch that reverts the revert, and fixes it for everyone else at the same time, @neilcsmith-net.

**Comment by neilcsmith-net** [comment]
@gohai yes, I'll see if that's feasible. But if it isn't, it's still far easier for a user to set a system property in a config file than rip apart the install to insert a patched JOGL file!

**Pull request merged**
