### PR TITLE
Serial: Make it possible to open a port based on USB IDs

### PR DESCRIPTION
**Pull request by gohai**
The proposed format is (Vendor ID)#(Product ID or IDs)#(Serial), where everything after the initial vendor ID is optional. The necessary code to get to the USB descriptors is currently implemented only for OS X and Linux, Windows forthcoming.

### CODE REVIEW

**Comment by benfry** [comment]
Couple thoughts: 

* If we add this, we should use the same syntax as the video library is using.

* I'm not nuts about the idea of having a bunch of constants defined that are tied to particular devices that have a shelf life of who knows what. It puts us in the position of deciding what goes in, and having the list be almost always out of date or at least a point of contention.

@shiffman @REAS thoughts?

**Comment by gohai** [comment]
Thanks @benfry, looking into video library syntax tomorrow.

**Comment by REAS** [comment]
I feel like I'm not knowledgable enough in this domain to have a strong opinion. I like the idea of making it easier to connect to devices, but I share @benfry's concerns about maintaining the list. I think it needs to be working with Windows when it's launched if it goes in.

**Comment by gohai** [comment]
Agree wrt Windows. I'll need some more time to have this working, aiming for two weeks from now..

**Comment by benfry** [comment]
Closing this in its current state. If we want to do something on these lines, we'll:

* Use the video syntax (as discussed above)
* Not include the constants... They belong in an Arduino library or something like that. I have no interest in making myself the target of the inevitable anger over what's included and what isn't.

**Pull request closed without merging**
