### PR TITLE
Set text color for InputMethod

### PR DESCRIPTION
**Pull request by tyfkda**
It is difficult to see the editing text,
because default text color might be similar to the background color:

ss

### CODE REVIEW

**Comment by benfry** [comment]
What's normal for this sort of thing in other editors? The 'before' seems like a bug, but the 'after' doesn't feel any more standard. What's the best way to handle this?

**Comment by tyfkda** [comment]
There is underline, so we can recognize editing text and I think this is standard way (and I don't change anything other than text color in this PR).

Other screenshot: Notepad (Windows):
notepad

**Comment by tyfkda** [comment]
Google Chrome textarea (Windows):
chrome_textarea

**Comment by benfry** [comment]
Ok, so this solution is a good start, though we should also set the background highlight color as well to the light blue.

**Comment by tyfkda** [comment]
I see.
I have changed to use same foreground/background color for editor.

**Comment by benfry** [comment]
Thanks for this. I've now incorporated your changes using a slightly different method, but they're now in there. Please give them a check to make sure I integrated them properly.

**Pull request closed without merging**
