### PR TITLE
Add accelerator key (mnemonics) for Japanese environment

### PR DESCRIPTION
**Pull request by crazymaster**
This will be able to apply other Asian languages.

ref: [Accelerator Keys — Localization Guide 0.9.0 documentation](http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/translation/accelerators.html)

> No available character. Usually in Asian languages where a keyboard is Western. Translate the word into your language and use the original English accelerator. Ie “&File” –> “XXXX(&F)”.

### CODE REVIEW

**Comment by crazymaster** [comment]
I tested on Linux and Windows.

**Comment by benfry** [comment]
Would you be interested in updating this?

**Comment by crazymaster** [comment]
This pull request doesn't consider that accelerator keys are unnecessary in macOS.

ref: https://support.apple.com/ja-jp/guide/mac-help/mchlp1446/mac
https://support.apple.com/ja-jp/guide/mac-help/hlpvw003/mac

**Comment by benfry** [comment]
Ok, that was going to be my next question.

**Pull request closed without merging**
