### PR TITLE
Make sure PImage.parent is set in loadImage()

### PR DESCRIPTION
**Pull request by JakubValtar**

### CODE REVIEW

**Comment by benfry** [comment]
Any idea where this regression came from?

**Comment by JakubValtar** [comment]
Probably https://github.com/processing/processing/pull/2966/commits/d0ada453ae152aee7437809789913e11f19ac31d#diff-29e1de29464981394819a89e38e87288L4681

**Comment by JakubValtar** [comment]
That is the merge commit, it's probably one of those 105 https://github.com/processing/processing/pull/2966/commits

**Comment by benfry** [comment]
Should have known from the commit message.

**Comment by JakubValtar** [comment]
Must've been Friday.

**Pull request merged**
