### PR TITLE
Low-WeakReference diet

### PR DESCRIPTION
**Pull request by JakubValtar**
- keeps the good stuff in
- no side effects
- Dr. C. stamp of approval

### CODE REVIEW

**Comment by codeanticode** [comment]
@JakubValtar I merged this PR, but then the framebuffer and texture resources in the test case I have been using:

```java
  public void settings() {
    size(640, 360, P2D);
     smooth(2);
  }

  public void setup() {
  }

  public void draw() {
      PGraphicsOpenGL pg = (PGraphicsOpenGL)createGraphics(width, height, P2D);
      pg.beginDraw();
      pg.background(random(255), random(255), random(255));
      pg.endDraw();
      image(pg, 0, 0);
  }  
```

don't get disposed. Could you double check?

**Comment by JakubValtar** [comment]
Ok I'm checking it now

**Comment by JakubValtar** [comment]
Why do you think so? Heap dump shows no letovers and when I put println() into disposeNative() I see that resources are deleted every GC cycle (which runs once every few seconds).

**Comment by codeanticode** [comment]
my mistake, sorry!

Yes, resource disposal is working great!

**Comment by JakubValtar** [comment]
Ah great, I was worried that there is something platform specific :)

**Pull request merged**
