### PR TITLE
Friendly Names for new Sketches

### LINKED ISSUE #6045: Friendly names for Processing Sketches like the p5.js web editor
## Description
Improvement: Friendly names for Processing Sketches like the p5.js web editor

## Expected Behavior
New sketches should have an easy-to-identify name.

## Current Behavior
New sketches are named with a number date string, sketch_201231b. This mix of numbers can make it hard to distinguish sketches, especially at a glance.

## Steps to Reproduce
1. Open Processing.
2. Create a new Sketch.
3. Create another new Sketch.
4. Try telling which sketch is which by quickly reading the name.

## Your Environment
* Processing version: 3/4
* Operating System and OS version: Windows 10, Version 1909, Build 18363.657
* Other information: 

## Possible Causes / Solutions
I have started a thread on [the Processing forum](https://discourse.processing.org/t/friendly-names-for-processing-sketches-like-the-p5-js-web-editor/).
I am interested in submitting a PR for this feature.

This is the current implementation:
image

Please find my branch [here](https://github.com/KartikSoneji/processing/tree/feature-friendly-names).

### PR DESCRIPTION
**Pull request by KartikSoneji**
Please refer to [this thread](https://discourse.processing.org/t/friendly-names-for-processing-sketches-like-the-p5-js-web-editor/) on the Processing forum.

Closes #6045 

Adds:
image

### CODE REVIEW

**Comment by KartikSoneji** [comment]
Oh, I thought `Closes issue` would work the same as `Closes`.  
Thanks for pointing it out! I'll make the changes.
Glad you liked the feature.

**Comment by benfry** [comment]
Thanks @KartikSoneji for this helpful and complete patch. I'd be happy to incorporate this with two changes: 

1. If you'd be willing to move the “friendly words” file to a file named `friendly.txt` in `build/shared/lib`, and load that on first use instead of making it a class, i.e. something like:

```java
	if (friendlyWords == null) {
        friendlyWords = PApplet.loadStrings(Base.getLibFile("friendly.txt"));
    }
```

2. Make this a PR against [the Processing 4 repo](https://github.com/processing/processing4) where current development is happening. 

Thanks again…

**Comment by KartikSoneji** [comment]
Hi @benfry !

Thanks for reviewing the changes, and I am glad you liked them.
I'll start porting the patch to Processing 4.

Can you please explain the benefits of loading the list of words on first use as opposed to having everything self-contained in one `.class` file?
I assume it is to decouple the list of words from the program source, but the list is unlikely to change.
On the other hand, loading a file adds additional complexity and one more point of failure (what happens if it cannot be loaded?)

**Comment by benfry** [comment]
Implemented for 4.0 beta 9, arriving shortly.

**Pull request closed without merging**
