### PR TITLE
Friendlier error message for HidingEnclosingType

### LINKED ISSUE #4228: Throw friendly error message instead of “The nested type cannot hide an enclosing type”
Hi, 

A student got this error because she named the class the same as the filename of the main sketch. Would it be possible to throw a friendlier error message? Like: "A class cannot have the same name as your the name of your sketch".

````
JitterBug bug;

void setup() {
  size(480, 120);
  bug = new JitterBug(width/2, height/2, 20);
}

void draw() {
  bug.move();
  bug.display();
}

class JitterBug {
  float x;
  float y; 
  int diameter;
  float speed = 2.5;

  JitterBug(float tempX, float tempY, int tempDiameter)  
  { 
    x = tempX;
    y = tempY;
    diameter = tempDiameter;
  }

  void move() {
      x += random(-speed, speed);
      y += random(-speed, speed);
  }

  void display() {
      ellipse(x, y, diameter, diameter);
  }
}
````

http://stackoverflow.com/questions/33902511/the-nested-type-cannot-hide-an-enclosing-type-class-java-processing

### PR DESCRIPTION
**Pull request by rzats**
This PR fixes #4228

### CODE REVIEW

**Comment by Akarshit** [comment]
@rzats Don't you think doing this would change the error message wherever an error of this type is occurring.
For example the code below would give the error message `The class Hello cannot have the same name as the name of your sketch`
```java
void setup(){
  size(300,300);
}
class Hello{
  int a;
  class Hello{
    int b;
  }
}
```

**Comment by rzats** [comment]
@Akarshit This makes sense - I've updated the preproc logic so that it actually checks the sketch name.

**Comment by benfry** [comment]
@rzats can you re-submit with the current version of the repo?

**Comment by rzats** [comment]
@benfry: sure - I'll open a new PR for this because syncing's going to be a bit hard at this point.

**Comment by benfry** [comment]
Thanks!

**Comment by rzats** [comment]
Resubmitted at #4451.

**Pull request closed without merging**
