### PR TITLE
CSVFile class Issue #5068

### PR DESCRIPTION
**Pull request by christianbender**
This class implements a data structure for handling of CSV-files.
For issue #5068 

### Overview about methods:

* CSVFile (String path, char seperator)
* CSVFile ( File file, char sperator)
* CSVFIle (char seperator)
* compile (String row, char seperator)
* isPunctuation (ch : char) : boolean
* getElementString(row : int, column : int) : string
* getElementDouble(row : int, column : int) : double
* addRow(row : string) : void
* commit() : void 
* commit(path : String) : void
    * commit(file : File ) : void
* findRow(key : string) : ArrayList<String>
* contains(key : string) : boolean
* getColumn(column : int) : ArrayList<String>
    * getColumn(key : string) : ArrayList<String>
* removeRow(key : string) : void 
    * removeRow(column : int) : void
* updateFile() : void
   * updateFile(file : File) : void
* getNumberOfRows() : int

### CODE REVIEW

**Comment by christianbender** [comment]
@JakubValtar  @all 

Why no response on the many pull request? Some PRs a addressed to issues with label "help wanted".

**Comment by benfry** [comment]
Hi Christian, we're working in our spare time and are often unable to address PRs, especially if they're not ready to go.

We can't accept this PR as-is. Rather than implementing delimiter support, it's a complete rewrite of the `Table` code that doesn't follow any of the conventions of the rest of the Processing source, adds a new class, and the implementation is significantly slower and less memory efficient than what's currently in the `Table` class. I know that code is complex, but it's that way in order to be more performant and also use memory in a way that allows us to load very large data sets.

**Comment by christianbender** [comment]
@benfry  
Ok, I understand. I will tried extended the Table class.
Thanks for your feedback.

**Comment by benfry** [comment]
Appreciate your understanding, and thank you for the help.

**Pull request closed without merging**
