### PR TITLE
Width fixing

### PR DESCRIPTION
**Pull request by Akarshit**
Possible fix for #3644

### CODE REVIEW

**Comment by benfry** [comment]
Waiting for word from @alignedleft

**Comment by alignedleft** [comment]
Will be checking this and my other items shortly.

**Comment by alignedleft** [comment]
screen shot 2015-08-21 at 11 37 10 am

Categories drop-down is 6-7 px too far to the right.

Is it difficult to get UI elements aligned like this? I didn't expect it would be.

**Comment by Akarshit** [comment]
@alignedleft It is extremely easy. The problem is that I don't have a Mac, I only have linux so I can't test this on Mac. Whatever PR i give works perfectly on linux.

**Comment by benfry** [comment]
So is this one ready to merge?

**Comment by alignedleft** [comment]
@benfry Yes, this is ready to merge and fixes #3644. Thanks!

**Pull request merged**
